repos:
- repo: local
  hooks:

  - id: mix-format
    name: 'elixir: mix format'
    entry: mix format --check-formatted
    language: system
    files: \.exs*$

  - id: mix-credo
    name: 'elixir: mix credo'
    entry: mix credo
    language: system
    pass_filenames: false
    files: \.exs*$


- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
